name: Building and Deploying Production.

on:
  push:
    branches:
      - master

jobs:
  building-deploing-production:

    runs-on: ubuntu-latest

    env:
      working-directory: ./frontend

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm packages.
        run: npm ci
        working-directory: ${{env.working-directory}}
      - name: Running npm build.
        run: npm run build --if-present
        working-directory: ${{env.working-directory}}
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_STAGING }}
          HEROKU_EMAIL: ${{ secrets.USER_EMAIL }}
      - name: Adding new build files to git
        run: git add .
      - name: Showing added files
        run: git status
      - name: Commiting changed files
        run: |
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_NAME
          git commit -m "GITHUB ACTIONS - ADDED BUILD."
        env:
          GITHUB_NAME: ${{ secrets.USER_NAME }}
          GITHUB_EMAIL: ${{ secrets.USER_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        run: |
          git push --force heroku master

