# Generated by Django 2.2.5 on 2021-06-28 13:56

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabRat',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('interactions', django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(), blank=True, size=None)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('bio_length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('caught_rats', django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(), blank=True, size=None)),
                ('escaped_rats', django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(), blank=True, size=None)),
                ('processing_rats', django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(), blank=True, size=None)),
            ],
        ),
    ]
